export const REQUEST_STARTED = 'REQUEST_STARTED'
export const REQUEST_FINISHED = 'REQUEST_FINISHED'
export const REQUEST_FAILED = 'REQUEST_FAILED'

export const LOAD_POKEMON_SUCCESS = 'LOAD_POKEMON_SUCCESS'
